dist: trusty
sudo: false

language: python
python:
  - "3.6"

# command to install dependencies
# Install with local setup.py, then install pytest
install:
  - pip install .
  - pip install pytest
#  - "pip install -r requirements.txt"

addons:
  apt_packages:
    - pandoc

# command to run tests
script:
  - PYTHONPATH=. make travis_test

#after_success:
#  coveralls

# whitelist
#branches:
#  only:
#    - master
#branches:
#  except:
#  - notravis
